# Generated by Django 5.1.2 on 2024-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_i_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_i',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
